[package]
name = "libportalfigure"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
glob = "0.3.3"
rusqlite = "0.37.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.8"
